//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearninGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int Sno { get; set; }
        public Nullable<int> Id { get; set; }
        public string SocialMediaType { get; set; }
        public string socialmediaurl { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
