//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearninGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProfile
    {
        public Nullable<int> Id { get; set; }
        public string StudentFullName { get; set; }
        public long PhoneNumber { get; set; }
        public string ImageUrl { get; set; }
        public string About { get; set; }
        public string StudentAddress { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
